### ISSUE TITLE
cors

### ISSUE THREAD

**Issue by MelHern** [devbaji/vue3-google-login#53] opened 2024-01-19 13:39 UTC
CORS ERROR  when select the account to login....

**Comment by devbaji** [comment] 2024-02-18 15:08
@MelHern Can you please provide more detail? Mention the device and browser name on which you are testing.

**Comment by devbaji** [comment] 2024-02-18 16:02
@MelHern Looks like this is a duplicate of this issue https://github.com/devbaji/vue3-google-login/issues/40

**Closed by devbaji** 2024-02-18 16:02 UTC
